In [2]:
import pandas as pd 
import numpy as np

In [3]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
# Converting to datetime datatype

date['date']=pd.to_datetime(date['date'])

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [14]:
date['date_year']=date['date'].dt.year
date.sample(10)

          date  product_id  city_id  orders  date_year  date_day
254 2019-05-07        5329       21       1       2019         7
414 2018-11-20        1670       26      15       2018        20
524 2019-12-01         370       13       7       2019         1
162 2019-11-17        1775       25       4       2019        17
133 2018-07-23        6564       18       3       2018        23
793 2019-08-19        5448        1      12       2019        19
226 2018-10-31        4036       13       1       2018        31
290 2018-12-05        4254       16      37       2018         5
870 2019-08-10        3800       16       2       2019        10
115 2018-10-13        5779       13       6       2018        13

In [18]:
date['date_day']=date['date'].dt.day
date.sample(5)

          date  product_id  city_id  orders  date_year  date_day
162 2019-11-17        1775       25       4       2019        17
28  2019-04-20        5501       16       1       2019        20
150 2019-07-10        7478       24       9       2019        10
465 2018-09-13        6566       18       8       2018        13
626 2019-12-07        6668       28       1       2019         7

In [19]:
date['date_month']=date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_day  date_month
106 2019-01-20        6592       25      11       2019        20           1
785 2019-11-28        7427       28       1       2019        28          11
955 2018-11-05        5738       13      42       2018         5          11
503 2018-12-02          25       18       1       2018         2          12
338 2018-12-05        3862        9       1       2018         5          12

In [23]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_day,date_month,date_month_name,date_dow
0,2019-12-10,5628,25,3,2019,1,12,December,1
1,2018-08-15,3646,14,157,2018,2,8,August,2
2,2018-10-23,1859,25,1,2018,1,10,October,1
3,2019-08-17,7292,25,1,2019,5,8,August,5
4,2019-01-06,4344,25,3,2019,6,1,January,6

In [24]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_day,date_month,date_month_name,date_dow
0,2019-12-10,5628,25,3,2019,1,12,December,1
1,2018-08-15,3646,14,157,2018,2,8,August,2
2,2018-10-23,1859,25,1,2018,1,10,October,1
3,2019-08-17,7292,25,1,2019,5,8,August,5
4,2019-01-06,4344,25,3,2019,6,1,January,6

In [25]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_day,date_month,date_month_name,date_dow,date_dow_name
0,2019-12-10,2019,1,12,December,1,Tuesday
1,2018-08-15,2018,2,8,August,2,Wednesday
2,2018-10-23,2018,1,10,October,1,Tuesday
3,2019-08-17,2019,5,8,August,5,Saturday
4,2019-01-06,2019,6,1,January,6,Sunday

In [28]:
date['date_is_weekend']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)




date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_day,date_month,date_month_name,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,1,12,December,1,Tuesday,0
1,2018-08-15,2018,2,8,August,2,Wednesday,0
2,2018-10-23,2018,1,10,October,1,Tuesday,0
3,2019-08-17,2019,5,8,August,5,Saturday,1
4,2019-01-06,2019,6,1,January,6,Sunday,1

In [31]:
date['date_week'] = date['date'].dt.isocalendar()['week'] 
date.head()

,date,product_id,city_id,orders,date_year,date_day,date_month,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,1,12,December,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,2,8,August,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,1,10,October,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,5,8,August,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,6,1,January,6,Sunday,1,1

# extract time between date

In [34]:
import datetime 
today=datetime.datetime.today() 
today

datetime.datetime(2026, 4, 2, 1, 0, 7, 144305)

In [35]:
today-date['date']

0     2305 days 01:00:07.144305
1     2787 days 01:00:07.144305
2     2718 days 01:00:07.144305
3     2420 days 01:00:07.144305
4     2643 days 01:00:07.144305
                 ...
995   2733 days 01:00:07.144305
996   2674 days 01:00:07.144305
997   2522 days 01:00:07.144305
998   2587 days 01:00:07.144305
999   2361 days 01:00:07.144305
Name: date, Length: 1000, dtype: timedelta64[ns]

In [38]:
(today-date['date']).dt.days

0      2305
1      2787
2      2718
3      2420
4      2643
       ...
995    2733
996    2674
997    2522
998    2587
999    2361
Name: date, Length: 1000, dtype: int64

In [40]:
# Months passed

np.round((today - date['date']) / np.timedelta64(1, 'D') / 30.44, 0)

0      76.0
1      92.0
2      89.0
3      80.0
4      87.0
       ...
995    90.0
996    88.0
997    83.0
998    85.0
999    78.0
Name: date, Length: 1000, dtype: float64

# working on time

In [41]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [42]:
time['date']=pd.to_datetime(time['date'])

In [43]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [44]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [45]:
today - time['date']

0     4491 days 00:10:07.144305
1     4355 days 01:20:07.144305
2     4841 days 00:39:07.144305
3     4143 days 00:29:07.144305
4     4540 days 01:49:07.144305
                 ...
995   5130 days 00:10:07.144305
996   4451 days 01:46:07.144305
997   4916 days 01:23:07.144305
998   5032 days 01:26:07.144305
999   4304 days 01:35:07.144305
Name: date, Length: 1000, dtype: timedelta64[ns]

In [46]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.880230e+08
1      3.762768e+08
2      4.182647e+08
3      3.579569e+08
4      3.922625e+08
           ...
995    4.432326e+08
996    3.845728e+08
997    4.247474e+08
998    4.347700e+08
999    3.718713e+08
Name: date, Length: 1000, dtype: float64

In [47]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      107784.168651
1      104521.335318
2      116184.651985
3       99432.485318
4      108961.818651
           ...
995    123120.168651
996    106825.768651
997    117985.385318
998    120769.435318
999    103297.585318
Name: date, Length: 1000, dtype: float64